### ISSUE TITLE
ckpt_path='/home/zrh/code/ckpt/ckpt_T.pth' error

### ISSUE THREAD

**Issue by wakakkakak** [stdcoutzrh/BuildingExtraction#12]
Hello, thank you for your great contribution! When I retrained the dataset of massbuilding , the code ran with the following error.I set ckpt_path='/home/zrh/code/ckpt/ckpt_T.pth' to 'ckpt_path=None' and it still reported an error. Could you please tell me how to fix this problem?
Traceback (most recent call last):
  File "D:\code\BuildFormer-main\train_supervision.py", line 234, in <module>
    main()
  File "D:\code\BuildFormer-main\train_supervision.py", line 213, in main
    config = py2cfg(args.config_path)
  File "D:\code\BuildFormer-main\tools\cfg.py", line 67, in py2cfg
    cfg_dict = py2dict(file_path)
  File "D:\code\BuildFormer-main\tools\cfg.py", line 59, in py2dict
    mod = import_module(module_name)
  File "D:\Python\Anaconda\envs\building\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\code\BuildFormer-main\config\massbuilding\sdscunet.py", line 38, in <module>
    net = create_shunted_unet_model(n_classes=2)
  File "D:\code\BuildFormer-main\geoseg\models\SDSCUNet.py", line 681, in create_shunted_unet_model
    model.load_from(ckpt_path)
  File "D:\code\BuildFormer-main\geoseg\models\SDSCUNet.py", line 645, in load_from
    pretrained_dict = torch.load(pretrained_path, map_location=device)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Python\Anaconda\envs\building\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/zrh/code/ckpt/ckpt_T.pth'
current model Params: 21.3194 M
pretrained_path:/home/zrh/code/ckpt/ckpt_T.pth

**Comment by Hitori-Bocchi** [comment]
我也遇到了，咋处理啊，不会
